function sinphasePlot()
    x = linspace(0, 0.5, 50);
    plot(x, sin(x * 5e6 * 1e-6 * 2 * pi), 'g-*', ...
         x, sin(x * 5e6 * 1e-6 * 2 * pi + pi / 2), 'k:o', ...
        'LineWidth', 1);
    xlabel('\bf Time (μs)', ...
           'FontName', 'Courier New');
    ylabel("{\it 'Normalized'} Signals ");
    title('In-Phase (\itsolid\it) and Quadrature (\itdotted\it) Signals', ...
          'FontSize', 14, ...
          'FontWeight' , 'normal');
    ylim([-1.5 1.5]);
    annotation('doublearrow', [0.42 0.52], [0.82 0.82], ...
               'LineStyle', '--', ...
               'LineWidth', 1);
    text(0.23, 1.2, 'π/2 phase lag', ...
         'HorizontalAlignment', 'center');
end